### ISSUE TITLE
YAML config parsing

### ISSUE THREAD

**Issue by bastienboutonnet** [bastienboutonnet/sheetload#1]
Ability to override column datatypes is often needed. 
For each sheet we should be able to override column dtypes. Config file should look something like that:
```
- sheet: Nice Human Readable Name
  skeey_key: 182391287391wjkajhdak82912387 
   - columns:
     col_a: int
     col_b: datetime[64,ns]
```
